### DISCUSSION TITLE
HA Sensors - Beko WDIK854411F washer dryer

### DISCUSSION THREAD

**Discussion by townsmcp** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#252] [Q&A] [answered]
Hi,
I am contemplating getting a Beko washer dryer wifi version with HomeWhiz integration. What sensors are generally exposed?
Most importantly, are instant energy consumption sensors exposed ie to know how many watts the machine is currently using?
Thanks

**Comment by TechHummel** [comment]
Maybe this differs among models, but I do not have an energy consumption sensor for my Beko washer / dryer (Bluetooth).

**Comment by townsmcp** [comment, marked as answer]
I thought I would just update this thread in case anyone in the future has a similar request to understand the exposed entities for a wifi washer/dryer.
So I ordered a Beko WDIK854411F washer dryer (flagged as new model on the Beko site, includes wifi). I have it integrated in HA now thanks to this integration :)
So, to first of all confirm, there is no energy consumption entity in HA. I guess potentially there might be energy consumption exposed in the HomeWhiz API?
The following entities are what I have had show up in HA from this integration (I have imaginatively named the machine `Washing Machine`:

### **Controls**
- Washing Machine AntiCrease = switch.washing_machine_anticrease
- Washing Machine Button Volume = select.washing_machine_button_volume
- Washing Machine Custom Duration Level = select.washing_machine_custom_duration_level
- Washing Machine Drying = select.washing_machine_drying
- Washing Machine Extra Rinse Count = select.washing_machine_extra_rinse_count
- Washing Machine Extra Water = switch.washing_machine_extra_water
- Washing Machine Night Mode = switch.washing_machine_night_mode
- Washing Machine None = switch.washing_machine_none
- Washing Machine None = switch.washing_machine_none_2
- Washing Machine Prewash = switch.washing_machine_prewash
- Washing Machine Programme = select.washing_machine_programme
- Washing Machine Smart Anti-Crease = switch.washing_machine_smart_anti_crease
- Washing Machine Soaking = switch.washing_machine_soaking
- Washing Machine Spin = select.washing_machine_spin
- Washing Machine State = select.washing_machine_state
- Washing Machine Steam = switch.washing_machine_steam
- Washing Machine Temperature = select.washing_machine_temperature
<img width="268" alt="image" src="https://github.com/user-attachments/assets/14dbb00f-8370-4de2-8cb4-0d5594ab63bd">

### **Sensors**
- Washing Machine Button Volume = sensor.washing_machine_button_volume
- Washing Machine Custom Duration Level = sensor.washing_machine_custom_duration_level
- Washing Machine Delay Start Time = sensor.washing_machine_delay_start_time
- Washing Machine Door is open = binary_sensor.washing_machine_door_is_open
- Washing Machine Drying = sensor.washing_machine_drying
- Washing Machine Duration = sensor.washing_machine_duration
- Washing Machine Extra Rinse Count = sensor.washing_machine_extra_rinse_count
- Washing Machine No water = binary_sensor.washing_machine_no_water
- Washing Machine Programme = sensor.washing_machine_programme
- Washing Machine Programme End Time = sensor.washing_machine_programme_end_time
- Washing Machine Remaining = sensor.washing_machine_remaining
- Washing Machine Remote control = binary_sensor.washing_machine_remote_control
- Washing Machine Safety = binary_sensor.washing_machine_safety
- Washing Machine Spin = sensor.washing_machine_spin
- Washing Machine Start Delay = sensor.washing_machine_start_delay
- Washing Machine State = sensor.washing_machine_state
- Washing Machine Sub state = sensor.washing_machine_sub_state
- Washing Machine Temperature = sensor.washing_machine_temperature
<img width="263" alt="image" src="https://github.com/user-attachments/assets/ba68eb68-f713-430c-b7be-1d4bdb160d98">




I will be honest, I dont understand yet what the 2 control `Washing Machine None` entities are

**Comment by townsmcp** [comment]
Update - I worked out what the 2 control devices are - 'Fast' and 'Fast+'

**Comment by wyntrblue** [comment]
just on the sensors, i just got a beko machine and was able to add it into HA without any problems. on the sensors however it shows "unavailable" for them all. how often does the integration poll for updates or am i missing something?

**Reply by townsmcp** [reply]
I have the same, especially if the machine is not turned on and set to Download mode. If you turn it on Download mode, close the door and press the button to operate form the app the sensors should populate. So far I have seen sensors updating roughly every minute? But I havent timed it yet so could be way out on that one.

**Comment by townsmcp** [comment]
As a side note, I have created  a consolidated device for all of the sensors - this single entity then helps drive a card (will add pictures and code soon in case anyone is interested). The consolidated device code is:
```
template:
  - sensor:
      - name: "Beko Washing Machine"
        unique_id: a3cb275d-8b80-4ea2-8c86-668b6e993b34
        icon: mdi:washing-machine
        state: >
          {% set state_map = {
              'device_state_off': 'Washer off',
              'device_state_on': 'Washer on',
              'device_state_running': 'Washing',
              'device_state_paused': 'Paused',
              'device_state_time_delay_active': 'Time delay active',
              'device_state_time_delay_paused': 'Time delay paused'
          } %}
          {{ state_map.get(states('sensor.washing_machine_state'), 'No state') }}
        attributes:
          programme: >
            {% set programme_map = {
                'program_cottons': 'Cottons',
                'program_eco_40_60': 'Eco 40-60',
                'program_mini_mini14': 'Xpress',
                'program_synthetics': 'Synthetics',
                'program_wool_handwash': 'Woollens/handwash',
                'program_shirts': 'Shirts',
                'program_mix': 'Mixed',
                'program_spin_pump': 'Spin & drain',
                'program_rinsing': 'Rinse',
                'program_dryer_cotton': 'Cotton Dry',
                'program_dryer_synthetics': 'Synthetic dry',
                'program_wash_dry': 'Wash & dry',
                'program_hygiene_plus': 'Hygiene+',
                'program_wash_wear': 'Wash & wear',
                'program_steam_therapy': 'Steam therapy/refresh',
                'program_outdoor_sports_goretex': 'Outdoor/sports',
                'program_darkwash_jeans': 'Dark (jeans)',
                'program_duvet_downwear': 'Duvet/down wear',
                'program_lingerie': 'Lingerie/delicates',
                'program_drum_clean': 'Drum clean+'
            } %}
            {{ programme_map.get(states('sensor.washing_machine_programme'), 'No programme') }}
          sub_state: >
            {% set sub_state_map = {
                'washer_substate_washing': 'Washing in progress',
                'washer_substate_rinsing': 'Rinsing',
                'washer_substate_spin': 'Spinning',
                'washer_substate_drying': 'Drying',
                'washer_substate_complete': 'Cycle complete',
                'washer_water_intake': 'Water intake',
                'washer_substate_prewash': 'Prewash',
                'washer_substate_softener': 'Softner',
                'washer_substate_program_started': 'Program started',
                'washer_substate_time_delay_enabled': 'Time delay enabled',
                'washer_substate_paused': 'Paused',
                'washer_substate_analysing': 'Analysing',
                'washer_substate_door_locked': 'Door locked',
                'washer_substate_opening_door': 'Door open',
                'washer_substate_locking_door': 'Locking door',
                'washer_substate_remove_laundry': 'Washing finished',
                'washer_substate_add_laundry': 'Add laundry',
                'washer_substate_rinse_hold': 'Hold',
                'washer_substate_remote_anticrease': 'Anticrease',
                'washer_substate_time_delay_paused': 'Time delay paused'
            } %}
            {{ sub_state_map.get(states('sensor.washing_machine_sub_state'), 'No sub state') }}
          duration: >
            {% set duration = states('sensor.washing_machine_duration') | int %}
            {% set hours = duration // 60 %}
            {% set minutes = duration % 60 %}
            {{ hours }}:{{ '{:02}'.format(minutes) }}:00
          delay_start_time: >
            {% set duration = states('sensor.washing_machine_delay_start_time') | int %}
            {% set hours = duration // 60 %}
            {% set minutes = duration % 60 %}
            {{ hours }}:{{ '{:02}'.format(minutes) }}:00
          programme_end_time: >
            {% set duration = states('sensor.washing_machine_programme_end_time') | int %}
            {% set hours = duration // 60 %}
            {% set minutes = duration % 60 %}
            {{ hours }}:{{ '{:02}'.format(minutes) }}:00
          remaining_time: >
            {% set duration = states('sensor.washing_machine_remaining') | int %}
            {% set hours = duration // 60 %}
            {% set minutes = duration % 60 %}
            {{ hours }}:{{ '{:02}'.format(minutes) }}:00
          door_open: >
            {% if is_state('binary_sensor.washing_machine_door_is_open', 'on') %}
              Open
            {% else %}
              Closed
            {% endif %}
          drying: >
            {% set drying_map = {
                'dry_off': 'Drying off',
                'dry_extra': 'Extra dry',
                'dry_cabinet': 'Cupboard dry',
                'dry_iron': 'Iron dry',
                'dry_10': 'Drying 10 minutes',
                'dry_20': 'Drying 20 minutes',
                'dry_30': 'Drying 30 minutes',
                'dry_60': 'Drying 60 minutes',
                'dry_90': 'Drying 90 minutes',
                'dry_120': 'Drying 120 minutes',
                'dry_150': 'Drying 150 minutes'
            } %}
            {{ drying_map.get(states('sensor.washing_machine_drying'), 'Unknown drying') }}
          extra_rinse_count: >
            {{ states('sensor.washing_machine_extra_rinse_count') }}
          no_water: >
            {% if is_state('binary_sensor.washing_machine_no_water', 'on') %}
              On
            {% else %}
              Off
            {% endif %}
          remote_control: >
            {% if is_state('binary_sensor.washing_machine_remote_control', 'on') %}
              On
            {% else %}
              Off
            {% endif %}
          safety: >
            {% if is_state('binary_sensor.washing_machine_safety', 'on') %}
              On
            {% else %}
              Off
            {% endif %}
          spin_speed: >
            {% set spin_speed_map = {
                'spin_no_spin': 'No spin',
                'spin_600': '600rpm',
                'spin_800': '800rpm',
                'spin_1200': '1200rpm',
                'spin_1400': '1400rpm',
                'spin_rinse_hold': 'Rinse hold'
            } %}
            {{ spin_speed_map.get(states('sensor.washing_machine_spin'), 'Unknown spin speed') }}
          start_delay: >
            {% set duration = states('sensor.washing_machine_start_delay') | int %}
            {% set hours = duration // 60 %}
            {% set minutes = duration % 60 %}
            {{ hours }}:{{ '{:02}'.format(minutes) }}:00
          end_time: >
            {% set end_time = states('sensor.washing_machine_programme_end_time') %}
            {% if end_time %}
              {{ as_datetime(end_time).strftime('%d-%m-%Y %I:%M %p') }}
            {% else %}
              Unknown
            {% endif %}
          temperature: >
            {% set temperature_map = {
                'temperature_cold_wash': 'Cold wash',
                'temperature_20': 'Temp 20°C',
                'temperature_30': 'Temp 30°C',
                'temperature_40': 'Temp 40°C',
                'temperature_60': 'Temp 60°C',
                'temperature_90': 'Temp 90°C'
            } %}
            {{ temperature_map.get(states('sensor.washing_machine_temperature'), 'Unknown temperature') }}


```
This will create a sensor that looks like the following:
![image](https://github.com/user-attachments/assets/69e1781b-031c-4a44-9911-e689435aeba2)

**Comment by townsmcp** [comment]
This sensor helps drive the following card:
```
type: custom:button-card
entity: sensor.washing_machine_combined_state
name: Washer dryer
show_label: true
state:
  - value: Washer off
    label: Turned off
    styles:
      card:
        - background: black
      name:
        - color: white
      icon:
        - color: white
      grid:
        - grid-template-areas: "\"i\" \"n\" \"l\""
        - grid-temnplate-columns: 1fr
        - grid-template-rows: 70px min-content 1fr
      label:
        - justify-self: start
        - font-size: 16px
        - font-weight: 500
        - padding: 2px 0
      custom_fields:
        program:
          - display: none
        bar:
          - display: none
        stat1:
          - display: none
        stat2:
          - display: none
        stat3:
          - display: none
styles:
  card:
    - padding: 20px
    - height: 180px
    - background: >-
        linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(121,9,116,1) 0%,
        rgba(0,212,255,1) 100%)
  grid:
    - grid-template-areas: "\"i program\" \"n stat2\" \"bar bar\" \"stat1 stat3\""
    - grid-template-columns: 1fr 1fr
    - grid-template-rows: 70px min-content 40px min-content
  name:
    - justify-self: start
    - font-size: 14px
    - opacity: 0.7
  icon:
    - width: 34px
  img_cell:
    - justify-self: start
    - align-self: start
    - width: 34px
    - height: 34px
  custom_fields:
    program:
      - justify-self: end
      - align-self: end
      - padding-bottom: 6px
      - font-size: 16px
      - font-weight: 500
    stat1:
      - justify-self: start
      - font-size: 10px
      - opacity: 0.7
    stat2:
      - justify-self: end
      - font-size: 16px
      - padding-bottom: 5px
      - font-weight: 500
    stat3:
      - justify-self: end
      - font-size: 10px
      - opacity: 0.7
    bar:
      - justify-self: start
      - margin-top: "-4px"
      - width: 100%
      - border-radius: 6px
      - background: black
      - height: 12px
custom_fields:
  program: |
    [[[ 
      return entity.state + " • " + entity.attributes.programme + " • " + entity.attributes.temperature + " • " + entity.attributes.sub_state
    ]]]
  bar: |
    [[[
      var state = states['sensor.washing_remain_percent'].state
      return `<div> <div style="background:white; height:
      12px; width: ${state}%"> </div> </div>`
    ]]]
  stat1: "0:00:00"
  stat2: |
    [[[ return entity.attributes.remaining_time + " minutes left"]]]
  stat3: >
    [[[ return entity.attributes.duration + " • End time: " +
    entity.attributes.end_time]]]

```
When the washer is off, the card looks like this:
<img width="479" alt="image" src="https://github.com/user-attachments/assets/eba85c62-04f8-42cf-bf21-decb5de97701">

When the washer is on, the card looks like this (ignore the size difference between these 2 images - they have been pulled from phone/desktop):
![IMG_1880](https://github.com/user-attachments/assets/fd96e8ee-e80b-4819-aafe-1c761514b2f9)


The sensor code to drive the percentage bar is:
```
template: 
  - sensor:
    - name: "Washing Remain Percent"
      unique_id: 731da6a7-fc1a-4911-976a-a45949d93d1c
      state: > 
          {% if state_attr('sensor.washing_machine_combined_state', 'remaining_time') == '0:00:00' %}
            0
          {% else %}
          {%- set start = state_attr('sensor.washing_machine_combined_state', 'duration') -%}
          {%- set end = state_attr('sensor.washing_machine_combined_state', 'remaining_time') -%}

          {%- set start_h = as_timestamp(strptime(start, '%H:%M:%S', '00:00:00')) | timestamp_custom("%H") | multiply(60) | round() -%}
          {%- set start_m = as_timestamp(strptime(start, '%H:%M:%S', '00:00:00')) | timestamp_custom("%M") | round() -%}
          {%- set start_s = ((as_timestamp(strptime(start, '%H:%M:%S', '00:00:00')) | timestamp_custom("%S") | int) / 60) | round(1) -%}
          {%- set end_h = as_timestamp(strptime(end, '%H:%M:%S', '00:00:00')) | timestamp_custom("%H") | multiply(60) | round() -%}
          {%- set end_m = as_timestamp(strptime(end, '%H:%M:%S', '00:00:00')) | timestamp_custom("%M") | round() -%}
          {%- set end_s = ((as_timestamp(strptime(end, '%H:%M:%S', '00:00:00')) | timestamp_custom("%S") | int) / 60) | round(1) -%}
          {%- set initial = start_h + start_m + start_s -%}
          {%- set consumed = initial -(end_h + end_m + end_s) -%}

          {{ 100 - ((consumed/initial)*100) | round() }}
          {% endif %}
```
