### ISSUE TITLE
AC integration is unavailable following a power outage

### ISSUE THREAD

**Issue by StancuFlorin** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#235]
After the a power outage, my home assistant is starting faster than my wifi router. Due to this, the HomeWhiz AC integration is unavailable.

The workaround is to manualy reload the integration or restart home assistant. 

I am using HomeWhiz 0.0.6 version.

**Comment by TechHummel** [comment]
Hi 👋 
So I guess that your AC is connected via WiFi?
Can you share any logs? I might be able to implement a retry logic if the connection is not successful.

**Comment by StancuFlorin** [comment]
At this moment I don't have access to that machine to play around. Meanwhile, I did the following automation as an workaround

```
alias: "Reload Beko AC Integration "
description: Reload Beko AC Integration when HA is back online
mode: single
triggers:
  - entity_id:
      - binary_sensor.8_8_8_8
    from: "off"
    to: "on"
    trigger: state
conditions: []
actions:
  - data: {}
    action: homeassistant.reload_config_entry
    target:
      entity_id: climate.beko_ac_ac

```
